Fix unbound registry entries causing startup crashes
error message:
```
Mob Loot Bags (mob_loot_bags) encountered an error while dispatching the net.neoforged.neoforge.registeries.RegisterEvent event
java.ang.NullPointerException: Block id not set

Mob Loot Bags (mob_loot_bags) encountered an error while dispatching the net.neoforged.neoforge.registeries.RegisterEvent event
java.ang.NullPointerException: Item id not set

Mob Loot Bags (mob_loot_bags) encountered an error while dispatching the net.neoforged.neoforge.registeries.RegisterEvent event
java.lang.NullPointerException: Trying to access unbount value: ResourceKey[minecraft:block / mob_loot_bags:loot_bag_recycle_lock]
```

changes:
ln 40-41; replaced the block factory method references with lambdas that directly construct each block using blockProperties(name).
ln 51-68; changed item registrations to use itemProperties(name) so their registry IDs are set correctly.
ln 106-117; helper methods.